name = "drive"
type = "webpack"
workers_dev = true
account_id = "46b418f552ce2c05e73d768cd4153639"
zone_id = "525033538cd3eaf2b48af04de59dca16"
kv_namespaces = [
    { binding = "BUCKET", id = "4cfb6bde9e0649769d6fb6cfc85f919a", preview_id = "ab2f5222eb4e4539b3f89b70eb3af8cb" }
]

[env.staging]
name = "drive-staging"
